# See https://pre-commit.com for more information
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: debug-statements
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: detect-private-key
      
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.9
    hooks:
      # Run the formatter
      - id: ruff-format
        args: ['--line-length=88']
      # Run the linter
      - id: ruff
        args: ['--fix', '--exit-non-zero-on-fix']
        
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: ['--strict', '--ignore-missing-imports']
        additional_dependencies:
          - pydantic>=2.0.0
          - types-aiofiles
          - types-python-dateutil
        exclude: '^tests/'
        
  - repo: https://github.com/python-poetry/poetry
    rev: 1.7.1
    hooks:
      - id: poetry-check
        files: pyproject.toml
        
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
      - id: forbid-tabs
      - id: remove-tabs
        
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.13.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
        
  - repo: local
    hooks:
      - id: no-commit-generated-files
        name: Block commits of generated files
        entry: Generated files should not be committed
        language: fail
        files: '^(NEWS\.md|CHANGELOG\.txt|DAILY_UPDATES\.md)$'