name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday

# Prevent concurrent runs on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    name: Test Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.12', '3.13']
        
    steps:
    - uses: actions/checkout@v5
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
      
    - name: Create virtual environment
      run: uv venv
      
    - name: Install dependencies
      run: |
        uv pip install -e .[dev]
        
    - name: Lint and format code
      run: |
        ./scripts/lint.sh
        
    - name: Test with pytest and generate Allure results
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: |
        uv run pytest tests/ -v --cov=src/git_ai_reporter --cov-report=xml --cov-report=term --alluredir=allure-results
        
    - name: Upload coverage to Codecov
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.12'
      uses: codecov/codecov-action@v5
      with:
        files: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}
        
    - name: Upload Allure results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-results-${{ matrix.os }}-${{ matrix.python-version }}
        path: allure-results/
        retention-days: 30

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
    - uses: actions/checkout@v5
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        
    - name: Install security tools
      run: |
        uv tool install bandit[toml]
        uv tool install safety
        
    - name: Run Bandit security scan
      run: |
        uv tool run bandit -r src/ -f json -o bandit-report.json
        
    - name: Check dependencies for vulnerabilities
      run: |
        uv tool run safety check --json
        
    - name: Upload security reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: security-reports
        path: |
          bandit-report.json
        retention-days: 30
        
  build:
    name: Build Distribution
    runs-on: ubuntu-latest
    needs: [test]
    permissions:
      contents: read
      attestations: write
      id-token: write
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        
    - name: Install build dependencies
      run: |
        uv tool install twine
        
    - name: Build package
      run: |
        uv build
        
    - name: Check package
      run: |
        uv tool run twine check dist/*
        
    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v2
      with:
        subject-path: 'dist/*'
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/
        retention-days: 30
        
  allure-report:
    name: Generate and Deploy Allure Report
    runs-on: ubuntu-latest
    needs: [test]
    if: always() && (github.ref == 'refs/heads/main' || github.event_name == 'pull_request')
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
    - uses: actions/checkout@v5
    
    - name: Download all Allure results
      uses: actions/download-artifact@v4
      with:
        pattern: allure-results-*
        path: allure-results-all/
        merge-multiple: true
        
    - name: Setup Java for Allure
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Install Allure
      run: |
        wget https://github.com/allure-framework/allure2/releases/download/2.25.0/allure-2.25.0.tgz
        tar -xzf allure-2.25.0.tgz
        sudo mv allure-2.25.0 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/bin/allure
        
    - name: Generate Allure Report
      run: |
        allure generate allure-results-all/ --output allure-report/ --clean
        
    - name: Add Allure history
      run: |
        if [ -d "allure-report/history" ]; then
          cp -r allure-report/history/* allure-results-all/ 2>/dev/null || true
        fi
        allure generate allure-results-all/ --output allure-report/ --clean
        
    - name: Setup Pages
      if: github.ref == 'refs/heads/main'
      uses: actions/configure-pages@v4
      
    - name: Upload Pages artifact
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-pages-artifact@v3
      with:
        path: allure-report/
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      id: deployment
      uses: actions/deploy-pages@v4
      
    - name: Upload Allure report as artifact
      if: github.event_name == 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: allure-report-pr
        path: allure-report/
        retention-days: 7