name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday

# Prevent concurrent runs on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: Test Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.12', '3.13']
        
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install uv
      uses: astral-sh/setup-uv@cc8b0e4e1b85e4ce0a6bbe1a1e0c5db7906a9b1c # v3.2.5
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
      
    - name: Create virtual environment
      run: uv venv
      
    - name: Install dependencies
      run: |
        uv pip install -e .[dev]
        
    - name: Lint and format code
      run: |
        ./scripts/lint.sh
        
    - name: Test with pytest
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: |
        uv run pytest tests/ -v --cov=src/git_ai_reporter --cov-report=xml --cov-report=term
        
    - name: Upload coverage to Codecov
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.12'
      uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4.6.0
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    
    - name: Set up Python
      uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
      with:
        python-version: '3.12'
        
    - name: Install uv
      uses: astral-sh/setup-uv@cc8b0e4e1b85e4ce0a6bbe1a1e0c5db7906a9b1c # v3.2.5
      with:
        enable-cache: true
        
    - name: Install security tools
      run: |
        uv tool install bandit[toml]
        uv tool install safety
        
    - name: Run Bandit security scan
      run: |
        uv tool run bandit -r src/ -f json -o bandit-report.json
        
    - name: Check dependencies for vulnerabilities
      run: |
        uv tool run safety check --json
        
    - name: Upload security reports
      if: always()
      uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
      with:
        name: security-reports
        path: |
          bandit-report.json
        retention-days: 30
        
  build:
    name: Build Distribution
    runs-on: ubuntu-latest
    needs: [test]
    permissions:
      contents: read
      attestations: write
      id-token: write
    
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    
    - name: Set up Python
      uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
      with:
        python-version: '3.12'
        
    - name: Install uv
      uses: astral-sh/setup-uv@cc8b0e4e1b85e4ce0a6bbe1a1e0c5db7906a9b1c # v3.2.5
      with:
        enable-cache: true
        
    - name: Install build dependencies
      run: |
        uv tool install build
        uv tool install twine
        
    - name: Build package
      run: |
        uv tool run python -m build
        
    - name: Check package
      run: |
        uv tool run twine check dist/*
        
    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@1c608d11d69870c2092266b3f9a6ac1a7d5e71dd # v1.4.3
      with:
        subject-path: 'dist/*'
        
    - name: Upload artifacts
      uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
      with:
        name: dist
        path: dist/
        retention-days: 30